Blogpost/urls.py
from django.urls import path
from Blogpost.views import PostList, PostDetail, likeView

app_name = 'Blogpost'
urlpatterns = [
    path('', PostList.as_view(), name = 'post-list'),
    path('detail/<int:pk>/', PostDetail.as_view(),name = 'post-detail'),
    path('ajax/likes/',likeView, name = 'like'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Blogpost.urls')),
    ] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

Blogpost/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now)
    img = models.ImageField(upload_to = '')
    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

Blogpost/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from Blogpost.models import Post
from django.http import JsonResponse
# Create your views here.

class PostList(ListView):
    model = Post

class PostDetail(DetailView):
    model = Post

def likeView(request):
    if request.method == "GET":
        i = request.GET.get('i',None)
        p = Post.objects.get(id = 0)
        p.likes += 1
        p.save()
        data = {'i':p.likes}
    return JsonResponse(data)

templates/Blogpost/post_detail.html
{% extends 'base.html' %}
{% block content %}
<h3 id="h_id">{{object.title}}</h3><br>
<p id="btext">{{object.description}}</p><br><br>
<button type="button" class="btn btn-success" onclick="onClick()">Like</button>
<p id="like">{{object.likes}}</p>
Published on {{object.timestamp}}
<input type="hidden" id="likes_id" name="name" value="{{object.id}}"> 
{% endblock %}

templates/Blogpost/post_list.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
{% for i in object_list %}
<div class="col-6">
<a id="h_id" href="{% url 'Blogpost:post-detail' i.id %}">{{i.title}}</a><br>
{% if i.img %}
<img src="{{i.img.url}}" alt="noimg" height="300" width="300">
{% endif %}
<br>
<br>
</div>
{% endfor %}
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<script src="{% static 'js/script.js' %}" type="text/javascript"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light ">
		<a class="navbar-brand" href="#">Navbar</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item active">
			  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item dropdown">
			  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Dropdown
			  </a>
			  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<a class="dropdown-item" href="#">Action</a>
				<a class="dropdown-item" href="#">Another action</a>
				<div class="dropdown-divider"></div>
				<a class="dropdown-item" href="#">Something else here</a>
			  </div>
			</li>
			<li class="nav-item">
			  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
			</li>
		  </ul>
		  <form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		  </form>
		</div>
	  </nav>
<div class="container">
{% block content %}
{% endblock %}
</div>

</body>
</html>